/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.fhdone.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

public class LoginForm extends ActionForm {

	private String userName;
	private String passWord;

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if( userName == null || userName.equals("")){
			errors.add("userName",new ActionMessage("username.error"));
			userName = null;
		}
		if( passWord == null || passWord.equals("")){
			errors.add("passWord",new ActionMessage("password.error"));
			passWord = null;
		}
		return errors;
	}

	public void reset(ActionMapping mapping, HttpServletRequest request) {
		userName = null;
		passWord = null;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWord() {
		return passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}
}