/*
 * Generated by XDoclet - Do not edit!
 */
package helloworld.interfaces;

import javax.ejb.EJBException;

/**
 * Remote interface for HelloWorld.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface HelloWorld
   extends javax.ejb.EJBObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public void replaceWithRealBusinessMethod(  )
      throws java.rmi.RemoteException;
   
   public String hello() throws java.rmi.RemoteException;

}
