/*
 * Generated by XDoclet - Do not edit!
 */
package helloworld.interfaces;

/**
 * Home interface for HelloWorld.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface HelloWorldHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HelloWorld";
   public static final String JNDI_NAME="ejb/HelloWorld";

   public helloworld.interfaces.HelloWorld create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
